### ISSUE TITLE
Counter doesn't update during Rendering

### ISSUE THREAD

**Issue by TidensBarn** [leomoon-studios/leomoon-textcounter#5]
Using Blender 2.80 and Textcounter 1.3.1, downloaded from leomoon.com.

I added a driver to the "Counter" property (Animated) with a simple python expression. Works as expected during playback and scrubbing in viewport, but doesn't update at all during animation rendering.

**Comment by leomoon** [comment]
Hello,

I tried scrubbing, viewport rendering and final rendering and they all worked. Could you please share a sample blend file?

**Comment by leomoon** [comment]
I was able to reproduce it.

Thanks for reporting. It will be fixed soon.

**Comment by leomoon** [comment]
This seems to be a Blender bug:
https://developer.blender.org/T71234

I'll close this when this is fixed by Blender developers.

**Comment by leomoon** [comment]
this issue has been fixed.

**Comment by foobarbecue** [comment]
Which versions do I need to use for this to not be broken? I've tried 2.81a and 2.82b and it's still a problem.

**Comment by foobarbecue** [comment]
Nevermind, it's fine with 1.3.3 and blender 2.81a

**Comment by sinterlesme** [comment]
Still i have the similar problem. Leomoon text counter works properly in the set up of my animation but when i start rendering is not moving. I just want it count up and move left to right, i arrange everything, hit play to preview my animation and it works properly, counting up and moving but when i hit the render animation; its counting up but not moving. I am getting crazy of it...

**Comment by leomoon** [comment]
This is still a Blender bug. Here is an update from the developers. This Blender bug is currently only fixed in 2.91.0 alpha.
https://developer.blender.org/T71234
